//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPractic3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int ID_People { get; set; }
        public string SurnamePeople { get; set; }
        public string NamePeople { get; set; }
        public string MiddleNamePeople { get; set; }
        public string WorkPost { get; set; }
        public string DateStartOfWork { get; set; }
        public string Salary { get; set; }
    }
}
